# Generated by Django 3.2.12 on 2022-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checkagain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckAgain',
        ),
    ]
