# Generated by Django 3.2.12 on 2022-04-15 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_checkagain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.TextField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='starting_point',
            field=models.TextField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
