# Generated by Django 3.2.12 on 2022-04-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tripphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.review'),
        ),
    ]
