# Generated by Django 3.2.12 on 2022-04-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_trip_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='review',
        ),
    ]
