# Generated by Django 3.2.12 on 2022-04-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_trip_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='number_of_passengers',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], default=1),
            preserve_default=False,
        ),
    ]
