# Generated by Django 3.2.12 on 2022-04-10 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220408_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
