# Generated by Django 3.2.12 on 2022-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_trip_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrip',
            name='popular_trip_photo',
            field=models.ImageField(upload_to='popular_trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tripphoto',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
